#!/bin/bash

rm -f *.exercise.out
#goodlines=$(grep -v "#" $inputfile| wc -l | cut -d ' ' -f1)

grep -v "#" blastoutput2.out > HSP_lines_only.out
unset IFS
unset dataline
#HSP score cuts chosen
group1cut=150
group2cut=250
group3cut=350
outfile1="HSPscore.$group1cut.exercise.out"
outfile2="HSPscore.$group2cut.exercise.out"
outfile3="HSPscore.$group3cut.exercise.out"
outfile4="HSPscore.morethan$group3cut.exercise.out"

#Delete reads from previous runs
rm -f $outfile1 $outfile2 $outfile3 $outfile4

##List all subject accessions for all HSPs
while read wholeline
do
if test ${wholeline:0:1} != "#"
   then
   dataline=$((dataline+1))
   echo "Line $dataline starts with ${wholeline:0:1}"


   read Q_acc S_acc pc_identity alignment_length mismatches gap_opens Q_start Q_end S_start S_end evalue bitscore <<< ${wholeline}   

   echo -e "$dataline\t$Q_acc\t$S_acc" >> Subject_accessions.exercise.out
done < $inputfile
